package lab02;

import java.util.ArrayList;
import java.util.Collections;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class QuanLySinhVien extends javax.swing.JFrame {

    ArrayList<SinhVien> danhSachSv = new ArrayList<>();

    /**
     * Creates new form QuanLySinhVien
     */
    public QuanLySinhVien() {
        initComponents();
        initComboBoxData();

    }

    public void fillToTable() {
        String[] coloums = {"HỌ VÀ TÊN", "ĐIỂM", "KHÓA HỌC", "XẾP LOẠI", "THƯỞNG"};
        DefaultTableModel tblModel = new DefaultTableModel(coloums, 0);
        for (SinhVien sv : danhSachSv) {
            Object[] thongTinSV = {sv.getTen(), sv.getDiem(), sv.getKhoaHoc(), sv.getXepLoai(), sv.isThuong()};
            tblModel.addRow(thongTinSV);
        }
        tblDanhSach.setModel(tblModel);
    }

    public void initComboBoxData() {
        String[] danhSach = {"Lập trình PHP cơ bản", "Lập trình JAVA cơ bản", "Lập trình C cơ bản", "Lập trình C# cơ bản", "Lập trình PYTHON cơ bản", "Lập trình HTML cơ bản"};
        DefaultComboBoxModel cboModel = new DefaultComboBoxModel(danhSach);
        cboKhoaHoc.setModel(cboModel);
    }

    public void addSinhVien() {
        SinhVien sv = new SinhVien();
        sv.setTen(txtTen.getText());
        sv.setDiem(Double.parseDouble(txtDiem.getText()));
        sv.setKhoaHoc((String) cboKhoaHoc.getSelectedItem());
        sv.setXepLoai(sv.XepLoai());
        sv.setThuong(sv.Thuong());
        
        danhSachSv.add(sv);
    }

    public void CapNhatSinhVien() {
        int index = tblDanhSach.getSelectedRow();
        if (index >= 0) {
            SinhVien st = danhSachSv.get(index);
            st.setTen(txtTen.getText());
            st.setDiem(Double.parseDouble(txtDiem.getText()));
            st.setKhoaHoc((String) cboKhoaHoc.getSelectedItem());
            st.setXepLoai(st.XepLoai());
            st.setThuong(st.Thuong());
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sinh viên");

        }
    }

    public void Doc() {
        int index = tblDanhSach.getSelectedRow();
        txtTen.setText(danhSachSv.get(index).getTen());
        txtDiem.setText(String.valueOf(danhSachSv.get(index).getDiem()));
        cboKhoaHoc.setSelectedItem(danhSachSv.get(index).getKhoaHoc());
        txtXepLoai.setText(danhSachSv.get(index).getXepLoai());
        cbxThuong.setSelected(danhSachSv.get(index).isThuong());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblTen = new javax.swing.JLabel();
        lblDiem = new javax.swing.JLabel();
        lblKhoaHoc = new javax.swing.JLabel();
        lblXepLoai = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        txtDiem = new javax.swing.JTextField();
        cboKhoaHoc = new javax.swing.JComboBox<>();
        txtXepLoai = new javax.swing.JTextField();
        cbxThuong = new javax.swing.JCheckBox();
        btnThem = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnNhapMoi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSach = new javax.swing.JTable();
        btnSapxeptheodiem = new javax.swing.JButton();
        btnSapxeptheoten = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("QUẢN LÝ HỌC VIÊN");

        lblTen.setText("HỌ VÀ TÊN");

        lblDiem.setText("ĐIỂM");

        lblKhoaHoc.setText("KHÓA HỌC");

        lblXepLoai.setText("XẾP LOẠI");

        cboKhoaHoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtXepLoai.setEditable(false);
        txtXepLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtXepLoaiActionPerformed(evt);
            }
        });

        cbxThuong.setText("Có Phần Thưởng?");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnCapNhat.setText(" CẬP NHẬT");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnXoa.setText("XÓA");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnNhapMoi.setText("NHẬP MỚI");
        btnNhapMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapMoiActionPerformed(evt);
            }
        });

        tblDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDanhSach);

        btnSapxeptheodiem.setText(" Sắp xếp theo điểm");
        btnSapxeptheodiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSapxeptheodiemActionPerformed(evt);
            }
        });

        btnSapxeptheoten.setText("Sắp xếp theo tên");
        btnSapxeptheoten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSapxeptheotenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnSapxeptheodiem)
                                .addGap(92, 92, 92)
                                .addComponent(btnSapxeptheoten))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblKhoaHoc, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                        .addComponent(lblDiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblXepLoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cboKhoaHoc, javax.swing.GroupLayout.Alignment.LEADING, 0, 442, Short.MAX_VALUE)
                                        .addComponent(txtDiem, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbxThuong, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(btnThem)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnCapNhat)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btnXoa)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btnNhapMoi))
                                        .addComponent(txtTen, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtXepLoai)))))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTen)
                            .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDiem)
                            .addComponent(txtDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblKhoaHoc))
                    .addComponent(cboKhoaHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblXepLoai)
                    .addComponent(txtXepLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(cbxThuong)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnCapNhat)
                    .addComponent(btnXoa)
                    .addComponent(btnNhapMoi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSapxeptheodiem)
                    .addComponent(btnSapxeptheoten))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNhapMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapMoiActionPerformed
        txtTen.setText(null);
        txtDiem.setText(null);
        txtXepLoai.setText(null);
        cbxThuong.setSelected(false);
    }//GEN-LAST:event_btnNhapMoiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        this.addSinhVien();
        fillToTable();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int indexXoa = tblDanhSach.getSelectedRow();
        if (indexXoa >= 0) {
            danhSachSv.remove(indexXoa);
            fillToTable();
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sinh viên");

        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        this.CapNhatSinhVien();;
        fillToTable();
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void tblDanhSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachMouseClicked
        Doc();
    }//GEN-LAST:event_tblDanhSachMouseClicked

    private void btnSapxeptheotenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSapxeptheotenActionPerformed
        Collections.sort(danhSachSv, (sv1, sv2) -> (sv1.getTen().compareTo(sv2.getTen())));
        fillToTable();
    }//GEN-LAST:event_btnSapxeptheotenActionPerformed

    private void btnSapxeptheodiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSapxeptheodiemActionPerformed
        Collections.sort(danhSachSv, (sv1, sv2) -> (int) (sv1.getDiem() - (sv2.getDiem())));
        fillToTable();
    }//GEN-LAST:event_btnSapxeptheodiemActionPerformed

    private void txtXepLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtXepLoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtXepLoaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLySinhVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnNhapMoi;
    private javax.swing.JButton btnSapxeptheodiem;
    private javax.swing.JButton btnSapxeptheoten;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboKhoaHoc;
    private javax.swing.JCheckBox cbxThuong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDiem;
    private javax.swing.JLabel lblKhoaHoc;
    private javax.swing.JLabel lblTen;
    private javax.swing.JLabel lblXepLoai;
    private javax.swing.JTable tblDanhSach;
    private javax.swing.JTextField txtDiem;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtXepLoai;
    // End of variables declaration//GEN-END:variables
}
